CRITICAL - 2023-07-26 07:27:56 --> Class "App\Controllers\Municipios" not found
in APPPATH\Controllers\ControllerMunicipios.php on line 10.
 1 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\ControllerMunicipios->cargarMunicipios()
 2 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerMunicipios))
 3 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-07-26 07:32:21 --> Class "App\Controllers\Municipios" not found
in APPPATH\Controllers\ControllerMunicipios.php on line 10.
 1 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\ControllerMunicipios->cargarMunicipios()
 2 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerMunicipios))
 3 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-07-26 16:29:43 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'db_ciudadanos' in C:\xampp\htdocs\ci4_ciudadanos_repaso\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'db_ciudadanos', 3306, '', 0)
#1 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\ci4_ciudadanos_repaso\app\Controllers\ControllerCiudadano.php(12): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\CodeIgniter.php(932): App\Controllers\ControllerCiudadano->cargarCiudadanos()
#8 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerCiudadano))
#9 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\ci4_ciudadanos_repaso\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'db_ciudadanos' in C:\xampp\htdocs\ci4_ciudadanos_repaso\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\ci4_ciudadanos_repaso\app\Controllers\ControllerCiudadano.php(12): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\CodeIgniter.php(932): App\Controllers\ControllerCiudadano->cargarCiudadanos()
#7 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerCiudadano))
#8 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4_ciudadanos_repaso\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-07-26 16:29:43 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'db_ciudadanos'
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `vciudadanos`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\ControllerCiudadano.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\ControllerCiudadano->cargarCiudadanos()
 7 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerCiudadano))
 8 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-07-26 16:30:00 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'db_ciudadanos' in C:\xampp\htdocs\ci4_ciudadanos_repaso\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'db_ciudadanos', 3306, '', 0)
#1 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\ci4_ciudadanos_repaso\app\Controllers\ControllerCiudadano.php(12): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\CodeIgniter.php(932): App\Controllers\ControllerCiudadano->cargarCiudadanos()
#8 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerCiudadano))
#9 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\ci4_ciudadanos_repaso\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'db_ciudadanos' in C:\xampp\htdocs\ci4_ciudadanos_repaso\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\ci4_ciudadanos_repaso\app\Controllers\ControllerCiudadano.php(12): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\CodeIgniter.php(932): App\Controllers\ControllerCiudadano->cargarCiudadanos()
#7 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerCiudadano))
#8 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4_ciudadanos_repaso\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-07-26 16:30:00 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'db_ciudadanos'
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `vciudadanos`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\ControllerCiudadano.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\ControllerCiudadano->cargarCiudadanos()
 7 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerCiudadano))
 8 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-07-26 16:30:09 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'db_ciudadanos' in C:\xampp\htdocs\ci4_ciudadanos_repaso\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'db_ciudadanos', 3306, '', 0)
#1 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\ci4_ciudadanos_repaso\app\Controllers\ControllerCiudadano.php(12): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\CodeIgniter.php(932): App\Controllers\ControllerCiudadano->cargarCiudadanos()
#8 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerCiudadano))
#9 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\ci4_ciudadanos_repaso\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'db_ciudadanos' in C:\xampp\htdocs\ci4_ciudadanos_repaso\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\ci4_ciudadanos_repaso\app\Controllers\ControllerCiudadano.php(12): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\CodeIgniter.php(932): App\Controllers\ControllerCiudadano->cargarCiudadanos()
#7 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerCiudadano))
#8 C:\xampp\htdocs\ci4_ciudadanos_repaso\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4_ciudadanos_repaso\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-07-26 16:30:09 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'db_ciudadanos'
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `vciudadanos`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\ControllerCiudadano.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\ControllerCiudadano->cargarCiudadanos()
 7 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerCiudadano))
 8 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
